<?php

  /*
    Sessions
    - Session Is Stored On The Server
    - Session Store Only A User Key In Cookie To Know Its You
    - Key Are Generated By PHP Engine So Its Almost Impossible To Guess
    - You Need To Add It Before Any Output
  */

  session_start();

  $_SESSION['name'] = "Ahmed";
  $_SESSION['id'] = 1005;

  echo '<pre>';
  print_r($_SESSION);
  echo '</pre>';

  echo '<a href="test.php">Test</a>';

  // =---------------------------------------------------------=

/*
    Sessions
    - Advanced Information
    - Edit
    - Views Count
  */

  // session_id("lkjsdklfjksdfsdf");

  session_start();

  // echo session_id();

  $_SESSION['name'] = "Elzero";

  isset($_SESSION['views']) ? $_SESSION['views']++ : $_SESSION['views'] = 1;

  echo "Hello " . $_SESSION['name'] . " Views Count Is " . $_SESSION['views'];

  echo '<a href="about.php">About</a>';

  // =---------------------------------------------------------=
  
  /*
    Sessions
    - Unset And Destroy
    - Login And Logout Simulation
  */

  session_start();

  // $_SESSION['name'] = "Elzero";
  // session_unset();
  // session_destroy();

  if ($_SERVER["REQUEST_METHOD"] === "POST") {
    if ($_POST['user'] === "Osama") {
      $_SESSION['username'] = "Elzero";
      $_SESSION['id'] = 1005;
    }
  }

  echo '<pre>';
  print_r($_SESSION);
  echo '</pre>';

  if (isset($_SESSION['username'])) {
    echo "Welcome " . $_SESSION['username'];
  } else {

?>

<form action="" method="POST">
  <input type="text" name="user">
  <input type="submit" value="Login">
</form>

<?php } ?>

<a href="logout.php">Logout</a>

  // =---------------------------------------------------------=

<?php

  /*
    Header
    - Send RAW HTTP Header To Client To Manipulate Info Sent By Web Server Before Any Output
    - You Can Use To Control Cache Or Force File Download

    header(Header[Required], Replace[Optional] = True, Response_Code[Optional])
  */

  // header("HTTP/1.0 404 Not Found");
  // header("expires: Sat, 01 Jan 2022 01:00:00");
  // header("cache-control: no-cache, must-revalidate");
  // echo "<a href='test.php'>Test</a>";
  // header("Refresh:5; url=test.php");
  header("Location: test.php");
  exit;

  // =---------------------------------------------------------=